name: ccl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cudatoolkit=11.3.1
  - flit-core=3.6.0
  - intel-openmp=2023.0.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuv=1.44.2
  - mkl=2023.0.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.9.16
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tbb=2021.7.0
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - appdirs==1.4.4
      - charset-normalizer==3.1.0
      - click==8.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - docker-pycreds==0.4.0
      - fonttools==4.39.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - idna==3.4
      - importlib-resources==5.12.0
      - kiwisolver==1.4.4
      - matplotlib==3.7.1
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - pathtools==0.1.2
      - pillow==9.4.0
      - protobuf==3.20.3
      - psutil==5.9.4
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pyyaml==6.0
      - quadprog==0.1.11
      - requests==2.28.2
      - sentry-sdk==1.17.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - tensorboardx==2.6
      - torch==1.13.1
      - torchsummary==1.5.1
      - torchvision==0.14.1
      - urllib3==1.26.14
      - wandb==0.14.0
      - xlsxwriter==3.1.2
      - zipp==3.15.0
